baseurl = "https://zealous-fermi-688a92.netlify.com/"
title = "Diário de Sombras"
theme = "ghostwriter"
languageCode = "en-us"
copyright = "Paulo Pinto"
#disqusShortname = "XXX"
#googleAnalytics = "XXX"

[Privacy]

[Privacy.disqus]
    disable = true

[Privacy.googleAnalytics]
    anonymizeIP = true
    respectDoNotTrack = true
    useSessionStorage = false

[Author]
    name = "Paulo Pinto"
    # profile = "https://google.com/+XXX"
    email = "paulopinto@protonmail.com"
    nick = "w3bk3rn3l"

[Taxonomies]
    tag = "tags"

[Params]
    mainSections = ["post"]
    intro = true
    headline = "DIÁRIO DE SOMBRAS"
    description = "e outras luzes"
    writeup = "jjj"
    github = "https://github.com/webkernel"
    # gitlab = "https://gitlab.com/XXX"
    # linkedin = "https://linkedin.com/in/XXX/"
    # gplus = "https://google.com/+XXX"
    twitter = "https://twitter.com/w3bk3rn3l"
    # stackoverflow = "https://stackoverflow.com/users/XXX/YYY"
    microblog = "https://micro.blog/w3bk3rn3l"
    # feedurl = "http://example.com/index.xml"
    # webmentionEndpoint = "https://example.com/webmention"
    # pingbackEndpoint = "https://example.com/pingback"
    # micropubEndpoint = "https://example.com/webmention/micropub"
    email = "paulopinto@protonmail.com"
    opengraph = true
    shareTwitter = true
    shareFacebook = true
    shareGooglePlus = false
    shareLinkedIn = true
    dateFormat = "Mon, Jan 2, 2006"
    highlightJsUrl = ""
    highlightJsLocalUrl = ""

[Permalinks]
    post = "/:year/:month/:day/:filename/"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Portefólio"
    url = "/project/"
    weight = 2

[[menu.main]]
    name = "Fotografia"
    url = "https://paulo-pinto.com/closetohome"
    weight = 3

[[menu.main]]
    name = "Autor"
    url = "/page/about/"
    weight = 4